domain_path: C:\Users\wolfg\dev\vitis\workspace\platform\export\platform\sw\standalone_microblaze_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
