# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PmodSWT/PmodSWT.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT || ORIG_REF_NAME==PmodSWT} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_axi_gpio_0_0/PmodSWT_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_axi_gpio_0_0 || ORIG_REF_NAME==PmodSWT_axi_gpio_0_0} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_clk_wiz_0_0/PmodSWT_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_clk_wiz_0_0 || ORIG_REF_NAME==PmodSWT_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_axi_uartlite_0_0/PmodSWT_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_axi_uartlite_0_0 || ORIG_REF_NAME==PmodSWT_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_microblaze_0_0/PmodSWT_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_microblaze_0_0 || ORIG_REF_NAME==PmodSWT_microblaze_0_0} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_dlmb_v10_1/PmodSWT_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_dlmb_v10_1 || ORIG_REF_NAME==PmodSWT_dlmb_v10_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_ilmb_v10_1/PmodSWT_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_ilmb_v10_1 || ORIG_REF_NAME==PmodSWT_ilmb_v10_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_dlmb_bram_if_cntlr_1/PmodSWT_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==PmodSWT_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_ilmb_bram_if_cntlr_1/PmodSWT_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==PmodSWT_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_lmb_bram_1/PmodSWT_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_lmb_bram_1 || ORIG_REF_NAME==PmodSWT_lmb_bram_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_mdm_1_1/PmodSWT_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_mdm_1_1 || ORIG_REF_NAME==PmodSWT_mdm_1_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_rst_clk_wiz_0_100M_1/PmodSWT_rst_clk_wiz_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_rst_clk_wiz_0_100M_1 || ORIG_REF_NAME==PmodSWT_rst_clk_wiz_0_100M_1} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_xbar_0/PmodSWT_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_xbar_0 || ORIG_REF_NAME==PmodSWT_xbar_0} -quiet] -quiet

# IP: bd/PmodSWT/ip/PmodSWT_microblaze_0_axi_periph_1/PmodSWT_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodSWT_microblaze_0_axi_periph_1 || ORIG_REF_NAME==PmodSWT_microblaze_0_axi_periph_1} -quiet] -quiet

# XDC: c:/Users/wolfg/dev/vivado/pmod/pmod.gen/sources_1/bd/PmodSWT/PmodSWT_ooc.xdc
